name: Build

on:
  - push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checking out for ${{ github.ref }}
        uses: actions/checkout@v2
      - run: |
          npm install
          npm run build
      - run: docker login https://ghcr.io -u compulim -p ${{ secrets.GITHUB_TOKEN }}
      - run: docker build -f controller.dockerfile . -t ghcr.io/compulim/experiment-acs-mockbot-controller:latest
      - run: docker push ghcr.io/compulim/experiment-acs-mockbot-controller:latest
      - run: docker build -f webserver.dockerfile . -t ghcr.io/compulim/experiment-acs-mockbot-webserver:latest
      - run: docker push ghcr.io/compulim/experiment-acs-mockbot-webserver:latest
